@echo off
echo Starting Okey Game System (Monorepo)...
echo Closing existing Node.js processes...
taskkill /F /IM node.exe >nul 2>&1
timeout /t 2 >nul

echo Installing dependencies (if needed)...
call npm install

echo Starting All Services (Shared, Server, Client)...
start "Okey Dev Environment" cmd /k "npm run dev"

echo Waiting for services to initialize...
timeout /t 10

echo Opening Game in Browser...
start http://localhost:3000
